site_name: 网络安全
site_url: https://mapan1984.github.io/network-security/
repo_url: https://github.com/mapan1984/network-security/
site_description: 非对称加密，数字证书与 CA，ssl 原理概述与应用
site_author: mapan

nav:
  - 0. 网络安全: 'README.md'
  - 1. ssl 原理概述:
    - '1-SSL 原理概述/README.md'
    - 1.1 非对称加密: '1-SSL 原理概述/1-非对称加密.md'
    - 1.2 证书与 CA: '1-SSL 原理概述/2-证书与 CA.md'
    - 1.3 SSL 协议: '1-SSL 原理概述/3-SSL 协议.md'
  - 2. 应用:
    - '2-应用/README.md'
    - 2.1 SSH 登录: '2-应用/1-SSH 登录.md'
    - 2.2 https: '2-应用/2-https.md'
  - 3. 实践手册:
    - '3-实践手册/README.md'
    - 3.1 OpenSSL 手册: '3-实践手册/1-OpenSSL 手册.md'
    - 3.2 keytool 手册: '3-实践手册/2-keytool 手册.md'
  - 4. 其他:
    - '4-其他/README.md'
    - 4.1 名称解释: '4-其他/1-名词解释.md'
    - 4.2 RSA 加密算法: '4-其他/2-RSA 加密算法.md'

# docs_dir: docs

theme:
  # name: readthedocs
  name: material
  language: 'zh'
  # palette:
  #   scheme: slate
  #   primary: blue grey
  #   accent: deep orange
  palette:
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - section-index
  - search:
      lang:
        - en
        - ja

extra_css: []


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
